require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.gitsigns"
require "user.bufferline"
require "user.lualine"
require "user.autopairs"
require "user.comments"
require "user.toggleterm"
require "user.treesitter"
require 'nvim-tree'.setup {}
